// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssiosjfukweuhkkzwdpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzaW9zamZ1a3dldWhra3p3ZHBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTE0NjYsImV4cCI6MjA2NzQ2NzQ2Nn0.xvrXUIHjRL5R-d_2WwkxzJgTpKstIhm1Fxp2O-_I2TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});